"""
Generates filtfilt ground-truth test vectors as a C++ header.
Usage: python3 gen_filtfilt_vectors.py <output_path>
"""
import sys
import numpy as np
from scipy.signal import butter, filtfilt


def fmt_array(arr):
    return ', '.join(f'{v:.17g}' for v in np.asarray(arr).ravel())


def write_case(f, label, order, cutoff, signal, irlen=None):
    b, a = butter(order, cutoff)
    y = filtfilt(b, a, signal, method='gust', irlen=irlen)

    for name, arr in (('b', b), ('a', a), ('x', signal), ('y', y)):
        f.write(f'static const double {name}_{label}[] = {{ {fmt_array(arr)} }};\n')
    f.write('\n')

    return {
        'label': label,
        'nb': len(b), 'na': len(a),
        'nx': len(signal), 'ny': len(y),
        'irlen': irlen or 0,
    }


if len(sys.argv) != 2:
    print(f'usage: {sys.argv[0]} <output_header>', file=sys.stderr)
    sys.exit(1)

rng = np.random.default_rng(42)
n   = 200

CASES = [
    ('random_noise',    4, 0.1,  rng.standard_normal(n),                                      None),
    ('sine_wave',       4, 0.1,  np.sin(2 * np.pi * 0.02 * np.arange(n)),                    None),
    ('step_function',   4, 0.1,  np.concatenate([np.zeros(n // 2), np.ones(n // 2)]),         None),
    ('high_order',      6, 0.05, rng.standard_normal(n),                                      None),
    ('irlen_truncated', 4, 0.1,  rng.standard_normal(n),                                      50),
]

with open(sys.argv[1], 'w') as f:
    f.write('// Auto-generated by gen_filtfilt_vectors.py — do not edit.\n')
    f.write('#pragma once\n')
    f.write('#include <cstddef>\n\n')
    f.write('namespace gen {\n\n')
    f.write('struct RawCase {\n')
    f.write('    const char*  label;\n')
    f.write('    const double* b; std::size_t nb;\n')
    f.write('    const double* a; std::size_t na;\n')
    f.write('    const double* x; std::size_t nx;\n')
    f.write('    const double* y; std::size_t ny;\n')
    f.write('    std::size_t  irlen;\n')
    f.write('};\n\n')

    meta = [write_case(f, *args) for args in CASES]

    f.write('static const RawCase kCases[] = {\n')
    for c in meta:
        lbl = c['label']
        f.write(f'    {{ "{lbl}", '
                f'b_{lbl}, {c["nb"]}, '
                f'a_{lbl}, {c["na"]}, '
                f'x_{lbl}, {c["nx"]}, '
                f'y_{lbl}, {c["ny"]}, '
                f'{c["irlen"]} }},\n')
    f.write('};\n\n')
    f.write(f'static const std::size_t kNumCases = {len(meta)};\n\n')
    f.write('} // namespace gen\n')
